name: Simple Deploy Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .
    - name: Run pytest
      run: |
        pytest --maxfail=1 --disable-warnings

  lint:
    name: Check code quality with ruff
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Run Ruff lint check
      run: |
        ruff check .

    - name: Run Ruff formatter (optional)
      run: |
        ruff format .

